---
- name: Install software on Fedora
  when: ansible_distribution == 'Fedora'
  become: True
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ fedora_software_list }}"
  failed_when: false

- name: Update software cache for pacman
  when: ansible_distribution == 'ArchLinux'
  become: True
  community.general.pacman:
    update_cache: yes
  changed_when: false

- name: Install software on ArchLinux
  when: ansible_distribution == 'ArchLinux'
  become: True
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ arch_software_list }}"

- name: Update software cache for apt-get
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: True
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false

- name: Install software on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  become: True
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_software_list }}"
  failed_when: false

- name: Install software on Debian
  when: ansible_distribution == 'Debian'
  become: True
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ debian_software_list }}"
  failed_when: false

- name: Install software on openSUSE
  when: ansible_os_family == 'Suse'
  become: true
  community.general.zypper:
    name: "{{ item }}"
    state: present
  with_items: "{{ opensuse_software_list }}"
