---
- name: Converge
  hosts: all
  vars:
    config_owner: ansible-test-user
  tasks:
    - name: "Include ansible-role-openbox2go"
      ansible.builtin.include_role:
        name: "ansible-role-openbox2go"
